name: fluid_bottom_nav_bar
description: A fluid bottom navigation bar
version: 0.0.1
homepage: https://github.com/eric-taix/fluid-nav-bar

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
